[package]
name = "create-bloom-filter"
version = "0.1.0"
authors = ["William Budington <bill@eff.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "1.0"
linecount = "0.1.0"
